swagger: "2.0"
info:
  title: proto/health/v1/health.proto
  version: version not set
tags:
  - name: HealthService
  - name: TelemetryService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/health:
    get:
      operationId: HealthService_CheckHealth
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CheckHealthResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - HealthService
  /v1/telemetry:
    get:
      operationId: TelemetryService_Telemetry
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1TelemetryResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - TelemetryService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CheckHealthResponse:
    type: object
    properties:
      status:
        type: string
  v1TelemetryResponse:
    type: object
    properties:
      status:
        type: string
      status2:
        type: string
